---

- name: Update VM's to portgroup
  hosts: vc1
  connection: local
  gather_facts: no

  vars:
    switch: S2-VMM
    vms:
    - name: RedHat_Demo-app
      portgroup: quarantine
    - name: RedHat_Demo-db
      portgroup: quarantine
    - name: RedHat_Demo-web
      portgroup: quarantine

  tasks:
  - name: Update VMs to quarantine
    vmware_guest:
     hostname: "{{ host }}"
     username: "{{ user }}"
     password: "{{ pass }}"
     datacenter: S2-DC
     validate_certs: no
     name: "{{ item.name }}"
     networks:
     - name: "{{ item.portgroup }}"
    delegate_to: localhost
    loop: "{{ vms }}"

  
- name: Cleanup MSO
  hosts: mso1
  connection: local
  gather_facts: no

  vars:
    tenant: RedHat_Ansible
    schema: RedHat Demo
    template: RedHat Template 1
    template2: RedHat Template 2
    vrf: vrf1
    bd: bd1
    ap: ap1
    epg1: db
    epg2: web
    epg3: app
    contract1: web2app
    contract2: app2db
    filter1: filter1
    filter2: filter2
    mso_login: &mso_login
     host: "{{ host }}"
     username: "{{ user }}"
     password: "{{ pass }}"
     validate_certs: no

  tasks:
  - name: Undeploy a schema template
    mso_schema_template_deploy:
     <<: *mso_login
     schema: "{{ schema }}"
     template: "{{ template }}"
     site: Miami
     state: undeploy
    delegate_to: localhost
  - name: Undeploy a schema template
    mso_schema_template_deploy:
     <<: *mso_login
     schema: "{{ schema }}"
     template: "{{ template2 }}"
     site: "San Francisco"
     state: undeploy
    delegate_to: localhost
  - name: Remove schema
    mso_schema:
     <<: *mso_login
     schema: "{{ schema }}"
     state: absent
    delegate_to: localhost

- name: Cleanup ACI
  hosts: apic2
  connection: local
  gather_facts: no

  vars:
    tenant: RedHat_Ansible
    ap: ap1
    epg1: db
    epg2: web
    epg3: app
    domain: S1-VMM

  tasks:
  - name: Remove tenant
    aci_tenant:
     host: "{{ host3 }}"
     username: "{{ user3 }}"
     password: "{{ pass3 }}"
     tenant: "{{ tenant }}"
     state: absent
     validate_certs: no
    delegate_to: localhost






